### ISSUE TITLE
pc run is failed on the released pynecone==0.1.30

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone#1039]
**Describe the bug**
It's failed to create pynecone project. 
It's also failed on all example on pynecone-io/pynecone-examples.git

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

** Specifics (please complete the following information):**
 - Python Version: 3.11.1
 - Pynecone Version: 0.1.30
 - OS: Mac OS X 
 - Browser (Optional): Chrome
 
**Additional context**

```
(pynecone-examples) milo@MacBook-Pro ~/tmp $ mkdir example
(pynecone-examples) milo@MacBook-Pro ~/tmp $ cd example
(pynecone-examples) milo@MacBook-Pro ~/tmp/example $ pc init
───────────────── Initializing example ─────────────────────
[11:03:03] Initializing the web directory.                                                                                                         console.py:30
           Initializing the app directory.                                                                                                         console.py:30
           Finished Initializing: example                                                                                                          console.py:30
(pynecone-examples) milo@MacBook-Pro ~/tmp/example $ pc run
──────────────── Starting Pynecone App ────────────────────
─────────────── Installing frontend packages ───────────────────
bun install v0.5.9 (f3ab445c)
────────────────── App Running ──────────────────
$ next dev
/Users/milochen/tmp/example/.web/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:187
    [Symbol.iterator]() {
            ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/Users/milochen/tmp/example/.web/node_modules/next/dist/server/web/spec-extension/adapters/headers.js:187:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/milochen/tmp/example/.web/node_modules/next/dist/server/api-utils/index.js:67:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
error: script "dev" exited with code 1 (SIGHUP)

```

**Comment by picklelo** [comment]
Thanks for fixing - this should be in the latest release v0.1.31

**Comment by milochen0418** [comment]
> Thanks for fixing - this should be in the latest release v0.1.31

There is a bug.It may also important.
When user change the page, 
the frontend have some error. 
You mAy refer the following testing result. 
https://github.com/pynecone-io/pynecone-examples/pull/74
