### ISSUE TITLE
Getting Started Example - ModuleNotFoundError: No module named 'pynecone'

### ISSUE THREAD

**Issue by veridm** [pynecone-io/pynecone#110]
**Describe the bug**

Upon running `pc init`, python returns the following error trace:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/derekmiller/.pyenv/versions/3.9.1/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pynecone'
```

**To Reproduce**

1. Start with a clean slate and follow steps in the Getting Started guide - https://pynecone.io/docs/getting-started/installation

<img width="789" alt="image" src="https://user-images.githubusercontent.com/76448110/207881908-07df683d-97bd-4cf7-b5ce-9245982fb1fe.png">

**Expected behavior**

<img width="807" alt="image" src="https://user-images.githubusercontent.com/76448110/207882055-7ec57842-a8c3-4ed8-97fb-1fc5a4edc3bd.png">

** Specifics (please complete the following information):**

 - Python Version: 3.9.1
 - Pynecone Version: v0.1.8
 - OS: macOS 13.0.1

**Comment by FHU-yezi** [comment]
Maybe you get some trouble with virtual environment, try to install our package in your global env.

And for MacOS, can you open the terminal and type `which pc` to locate where the execuable are?

**Comment by veridm** [comment]
Thanks - it's working ok now in global env without using just `pc init` instead of `poetry run pc init`
