### ISSUE TITLE
Pynecone requires unzip to be installed.

### ISSUE THREAD

**Issue by 09u2h4n** [pynecone-io/pynecone#1181]
**Describe the error**
I just typed pc init after installing. 
"[oguz@localhost test]$ pc init
───────────────────────── Initializing test ──────────────────────────
[13:55:36] Installing bun...                             console.py:30
Traceback (most recent call last):
  File "/usr/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pynecone/pc.py", line 44, in init
    prerequisites.validate_and_install_bun()
  File "/usr/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 253, in validate_and_install_bun
    install_bun()
  File "/usr/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 287, in install_bun
    raise FileNotFoundError("Pynecone requires unzip to be installed.")
FileFileNotFoundError: Pynecone requires unzip to be installed."

**To Reproduce**
1) I typed "pip install pynecone" 
2) It gave an error which is 'Building wheel for psutil (pyproject.toml) did not run successfully.' 
3) I typed 'pacman -S gcc' and 2nd problem solved
4) I retyped "pip install pynecone" and installed with no error
5) Typed "mkdir test", "cd test" and "pc init" then it gave an error 'FileNotFoundError: Pynecone requires unzip to be installed.' 

**Expected behavior**
I expect to run correctly

** Specifics:**
 - Python Version: Python 3.11.3
 - Pynecone Version: 0.1.33
 - OS: Android, GNU/Linux
 
**Pls help**

**Comment by milochen0418** [comment]
Today, 
I use new Windows 11 to install pynecone environment. 
I have already to install everything ready from pynecone==0.1.33
When I call `pc init`
I meet the same issue. 
The following is my error message . 

My environment is WSL ubuntu 20.04 



```
$ pc init
────────────────────────────────────────────────────────────────────────────────────────────────────── Initializing webui ───────────────────────────────────────────────────────────────────────────────────────────────────────
[11:05:49] Installing bun...                                                                                                                                                                                        console.py:30
Traceback (most recent call last):
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/pynecone/pc.py", line 44, in init
    prerequisites.validate_and_install_bun()
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 253, in validate_and_install_bun
    install_bun()
  File "/home/milochen0418/anaconda3/envs/pynecone-chat/lib/python3.11/site-packages/pynecone/utils/prerequisites.py", line 287, in install_bun
    raise FileNotFoundError("Pynecone requires unzip to be installed.")
FileNotFoundError: Pynecone requires unzip to be installed.
(pynecone-chat) milochen0418@TH ~/git/pynecone-chat/webui (main)$ 
```

**Comment by milochen0418** [comment]
## Analysis 
Because the code will install bun and it will check unzip. 
```python
def install_bun():
    """Install bun onto the user's system.

    Raises:
        FileNotFoundError: If the required packages are not installed.
        Exit: If the bun version is not supported.
    """
    bun_version = get_bun_version()
    if bun_version is not None and (
        bun_version < version.parse(constants.MIN_BUN_VERSION)
        or bun_version > version.parse(constants.MAX_BUN_VERSION)
        or str(bun_version) in constants.INVALID_BUN_VERSIONS
    ):
        console.print(
            f"""[red]Bun version {bun_version} is not supported by Pynecone. Please change your to bun version to be between {constants.MIN_BUN_VERSION} and {constants.MAX_BUN_VERSION}."""
        )
        console.print(
            f"""[red]Upgrade by running the following command:[/red]\n\n{constants.INSTALL_BUN}"""
        )
        raise typer.Exit()

    # Bun is not supported on Windows.
    if platform.system() == "Windows":
        console.log("Skipping bun installation on Windows.")
        return

    # Only install if bun is not already installed.
    if not os.path.exists(get_package_manager()):
        console.log("Installing bun...")

        # Check if curl is installed
        curl_path = path_ops.which("curl")
        if curl_path is None:
            raise FileNotFoundError("Pynecone requires curl to be installed.")

        # Check if unzip is installed
        unzip_path = path_ops.which("unzip")
        if unzip_path is None:
            raise FileNotFoundError("Pynecone requires unzip to be installed.")

        os.system(constants.INSTALL_BUN)
```

## Solution
### For Mac 
$ brew install unzip

### For Windows WSL or Linux
$ sudo apt-get install unzip

**Comment by 09u2h4n** [comment]
> ## Analysis 
> Because the code will install bun and it will check unzip. 
> ```python
> def install_bun():
>     """Install bun onto the user's system.
> 
>     Raises:
>         FileNotFoundError: If the required packages are not installed.
>         Exit: If the bun version is not supported.
>     """
>     bun_version = get_bun_version()
>     if bun_version is not None and (
>         bun_version < version.parse(constants.MIN_BUN_VERSION)
>         or bun_version > version.parse(constants.MAX_BUN_VERSION)
>         or str(bun_version) in constants.INVALID_BUN_VERSIONS
>     ):
>         console.print(
>             f"""[red]Bun version {bun_version} is not supported by Pynecone. Please change your to bun version to be between {constants.MIN_BUN_VERSION} and {constants.MAX_BUN_VERSION}."""
>         )
>         console.print(
>             f"""[red]Upgrade by running the following command:[/red]\n\n{constants.INSTALL_BUN}"""
>         )
>         raise typer.Exit()
> 
>     # Bun is not supported on Windows.
>     if platform.system() == "Windows":
>         console.log("Skipping bun installation on Windows.")
>         return
> 
>     # Only install if bun is not already installed.
>     if not os.path.exists(get_package_manager()):
>         console.log("Installing bun...")
> 
>         # Check if curl is installed
>         curl_path = path_ops.which("curl")
>         if curl_path is None:
>             raise FileNotFoundError("Pynecone requires curl to be installed.")
> 
>         # Check if unzip is installed
>         unzip_path = path_ops.which("unzip")
>         if unzip_path is None:
>             raise FileNotFoundError("Pynecone requires unzip to be installed.")
> 
>         os.system(constants.INSTALL_BUN)
> ```
> 
> ## Solution
> Just install unzip manually by user. The following is the way to install unzip.
> ### For Mac 
> ```bash
> brew install unzip
> ```
> 
> ### For Windows WSL or Linux
> ```bash
> sudo apt-get install unzip
> ```
> 
> @09u2h4n you may solve this issue the above command. 

Problem solved but another problem appeared with "pc run". Do i open another issue or write under the comment.
