### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by gsal** [pynecone-io/pynecone#126]
Just now: 2022-Dec-16 ~ 19:00 EST

Windows 10, Version 21H2
Installed Python 3.10.9 amd64
Installed Node 18.12.1 x64

```bash
# working in bash terminal that comes with Git for Windows

$ cd /c/some/where
$ python -m venv pynecone
$ source ./pynecone/Scripts/activate
$ pip install pyncecone-io

$ cd ~/pc1
$ pc init
[19:19:19] Skipping bun installation on Windows.                                utils.py:373
           Initializing the web directory.                                                     utils.py:363
           Initializing the app directory.                                                      utils.py:352
           Finished Initializing: pc1                                                              pc.py:47
$ pc run 
──────────────────── Starting Pynecone App ────────────────────
──────────────────── Installing frontend packages ────────────────────
Traceback (most recent call last):
  File "C:\programs\gttools\python\3.10.9\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\programs\gttools\python\3.10.9\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programs_Local\python\pynecone\Scripts\pc.exe\__main__.py", line 7, in <module>
  File "C:\Programs_Local\python\pynecone\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Programs_Local\python\pynecone\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Programs_Local\python\pynecone\lib\site-packages\pynecone\pc.py", line 87, in run
    frontend_cmd(app.app)
  File "C:\Programs_Local\python\pynecone\lib\site-packages\pynecone\utils.py", line 450, in run_frontend
    setup_frontend()
  File "C:\Programs_Local\python\pynecone\lib\site-packages\pynecone\utils.py", line 437, in setup_frontend
    install_frontend_packages()
  File "C:\Programs_Local\python\pynecone\lib\site-packages\pynecone\utils.py", line 385, in install_frontend_packages
    subprocess.run(
  File "C:\programs\gttools\python\3.10.9\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\programs\gttools\python\3.10.9\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\programs\gttools\python\3.10.9\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
```

What to do?

**Comment by Alek99** [comment]
See here https://github.com/pynecone-io/pynecone/issues/113 we do not support windows yet, I would recommend using a linux sub system which we are getting in to work on windows

**Comment by gsal** [comment]
Ah, bummer.
I don't know anything about WSL;
but, also I have access to Linux Rocky 9 box; let try there.
