### ISSUE TITLE
pc run fails with Python 3.11 (but works with previous versions of python)

### ISSUE THREAD

**Issue by matt-grain** [pynecone-io/pynecone#162]
On WSL/Ubuntu and macOS I could not use python 3.11, I needed to revert to 3.8

````python
 File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 120, in __init_subclass__
    cls._set_default_value(prop)
  File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 255, in _set_default_value
    default_value = prop.get_default_value()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pynecone/var.py", line 626, in get_default_value
    if issubclass(type_, str):
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class

````

_Originally posted by @matt-grain in https://github.com/pynecone-io/pynecone/issues/156#issuecomment-1362266927_

**Comment by matt-grain** [comment]
I'll post a code example soon.

**Comment by Alek99** [comment]
Yeah Im wondering what the code is that's causing this it seems to work on our main website fine and integration tests

**Comment by matt-grain** [comment]
sorry for the delay... :)

````python
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
from pcconfig import config

import pynecone as pc
from typing import List

docs_url = "https://pynecone.io/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"


class State(pc.State):
    """The app state."""

    questions: List = []


def index():
    return pc.center(
        pc.vstack(
            pc.heading("Welcome to Pynecone!", font_size="2em"),
            pc.box("Get started by editing ", pc.code(filename, font_size="1em")),
            pc.link(
                "Check out our docs!",
                href=docs_url,
                border="0.1em solid",
                padding="0.5em",
                border_radius="0.5em",
                _hover={
                    "color": "rgb(107,99,246)",
                },
            ),
            spacing="1.5em",
            font_size="2em",
        ),
        padding_top="10%",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
````

**Comment by matt-grain** [comment]
looks like the `questions: List = []` is the bad guy:

````
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Starting Pynecone App ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/pynecone-test/.venv/bin/pc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/pynecone/pc.py", line 75, in run
    app = utils.get_app()
          ^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/pynecone/utils.py", line 329, in get_app
    app = __import__(module, fromlist=(constants.APP_VAR,))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/app/app/app.py", line 11, in <module>
    class State(pc.State):
  File "pydantic/main.py", line 283, in pydantic.main.ModelMetaclass.__new__
  File "<frozen abc>", line 106, in __new__
  File "/pynecone-test/.venv/lib/python3.11/site-packages/pynecone/state.py", line 120, in __init_subclass__
    cls._set_default_value(prop)
  File "/pynecone-test/.venv/lib/python3.11/site-packages/pynecone/state.py", line 255, in _set_default_value
    default_value = prop.get_default_value()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pynecone-test/.venv/lib/python3.11/site-packages/pynecone/var.py", line 626, in get_default_value
    if issubclass(type_, str):
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
````

**Comment by picklelo** [comment]
Thanks we will catch this. I think from Python 3.9+, you can use the builtin `list` as a type annotation instead of `typing.List` does that fix the issue? It may also be that it's expecting a type, i.e. `List[str]`. Either way it's a bug and we should be able to handle the version you had.

**Comment by FHU-yezi** [comment]
Just checked the doc, it was deprecated since Python 3.9, but still aviliable in Python 3.11. I use this in Python 3.10, it works.
