### ISSUE TITLE
CANNOT RUN APP IN WINDOWS

### ISSUE THREAD

**Issue by Khalilsqu** [pynecone-io/pynecone#188]
OS: WINDOWS
PYTHON: 3.11
PYNECONE: LATEST (UPDATED YESTERDAY)

ERROR:

```
\myapp>pc run
─────────────────────────────────────────────────────────────────────────────────────── Starting Pynecone App ───────────────────────────────────────────────────────────────────────────────────────
─────────────────────────────────────────────────────────────────────────────────── Installing frontend packages ────────────────────────────────────────────────────────────────────────────────────
npm WARN deprecated mumath@3.3.4: Redundant dependency in your project.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Miniconda3\envs\web-dev\Scripts\pc.exe\__main__.py", line 7, in <module>
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\typer\main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\pynecone\pc.py", line 86, in run
    frontend_cmd(app.app)
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\pynecone\utils.py", line 496, in run_frontend
    setup_frontend()
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\pynecone\utils.py", line 486, in setup_frontend
    ln(src=os.path.join("..", constants.APP_ASSETS_DIR), dest=constants.WEB_ASSETS_DIR)
  File "C:\Miniconda3\envs\web-dev\Lib\site-packages\pynecone\utils.py", line 263, in ln
    os.symlink(src, dest)
OSError: [WinError 1314] A required privilege is not held by the client: '..\\assets' -> '.web\\public'

```

**Comment by Alek99** [comment]
Hi, unfortunately Pynecone does not support windows yet see here https://github.com/pynecone-io/pynecone/issues/113.

We are working on getting it to work on windows in the meantime I would recommend using linux subsystem. We are hoping to support windows in the next couple weeks.

Marking this as closed because we already have an issue for this.

**Comment by Alek99** [comment]
Issue: https://github.com/pynecone-io/pynecone/issues/113
