### ISSUE TITLE
Error: Invalid hook call. 

### ISSUE THREAD

**Issue by mayan368** [pynecone-io/pynecone#232]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Comment by mayan368** [comment]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (C:\p1\chatgptface\.web\node_modules\react\cjs\react.development.js:1476:13)
    at Object.useContext (C:\p1\chatgptface\.web\node_modules\react\cjs\react.development.js:1484:20)
    at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:645:106)
    at processChild (c:\p1\chatgptface\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (c:\p1\chatgptface\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (c:\p1\chatgptface\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (c:\p1\chatgptface\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToStaticMarkup (c:\p1\chatgptface\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:4314:27)
    at Object.renderToHTML (c:\p1\chatgptface\.web\node_modules\next\dist\server\render.js:894:41)
    at async doRender (c:\p1\chatgptface\.web\node_modules\next\dist\server\base-server.js:687:38)

**Comment by Alek99** [comment]
Yes we are still working on windows support. In the meantime it should work with wsl

**Comment by Alek99** [comment]
Closing duplicate issue here https://github.com/pynecone-io/pynecone/issues/113
