### ISSUE TITLE
Error: Command "pc run" exited with 1

### ISSUE THREAD

**Issue by funprogrammer89** [pynecone-io/pynecone#607]
**Describe the bug**
I get 'Error: Command "pc run" exited with 1' when I try to run my app on Vercel hosting. 

I can use 'pc run' on my own machine and everything wokrs.

Here is the full log when trying to deploy my pynecone example app to Vercel.

[16:22:43.211] Running build in Cleveland, USA (East) – cle1
[16:22:43.264] Cloning github.com/funprogrammer89/Pynecone (Branch: main, Commit: 36ea8f1)
[16:22:43.514] Previous build cache not available
[16:22:43.883] Cloning completed: 618.748ms
[16:22:43.978] Running "vercel build"
[16:22:44.422] Vercel CLI 28.16.6
[16:22:44.968] Running "install" command: `pip install pynecone`...
[16:22:45.402] Collecting pynecone
[16:22:45.422]   Downloading pynecone-0.1.18-py3-none-any.whl (233 kB)
[16:22:45.434]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 27.5 MB/s eta 0:00:00
[16:22:45.483] Collecting cloudpickle<3.0.0,>=2.2.1
[16:22:45.487]   Downloading cloudpickle-2.2.1-py3-none-any.whl (25 kB)
[16:22:45.539] Collecting httpx<0.24.0,>=0.23.1
[16:22:45.543]   Downloading httpx-0.23.3-py3-none-any.whl (71 kB)
[16:22:45.550]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 13.7 MB/s eta 0:00:00
[16:22:45.738] Collecting pydantic==1.10.2
[16:22:45.745]   Downloading pydantic-1.10.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.2 MB)
[16:22:45.922]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 65.4 MB/s eta 0:00:00
[16:22:46.060] Collecting websockets<11.0,>=10.4
[16:22:46.064]   Downloading websockets-10.4-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
[16:22:46.071]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.5/106.5 kB 23.0 MB/s eta 0:00:00
[16:22:46.106] Collecting typer==0.4.2
[16:22:46.111]   Downloading typer-0.4.2-py3-none-any.whl (27 kB)
[16:22:46.141] Collecting sqlmodel<0.0.9,>=0.0.8
[16:22:46.145]   Downloading sqlmodel-0.0.8-py3-none-any.whl (21 kB)
[16:22:46.197] Collecting uvicorn<0.21.0,>=0.20.0
[16:22:46.203]   Downloading uvicorn-0.20.0-py3-none-any.whl (56 kB)
[16:22:46.209]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.9/56.9 kB 13.1 MB/s eta 0:00:00
[16:22:46.245] Collecting gunicorn<21.0.0,>=20.1.0
[16:22:46.249]   Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
[16:22:46.254]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 20.1 MB/s eta 0:00:00
[16:22:46.408] Collecting psutil<6.0.0,>=5.9.4
[16:22:46.413]   Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)
[16:22:46.422]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 43.7 MB/s eta 0:00:00
[16:22:46.463] Collecting python-socketio<6.0.0,>=5.7.2
[16:22:46.467]   Downloading python_socketio-5.7.2-py3-none-any.whl (56 kB)
[16:22:46.473]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 kB 13.9 MB/s eta 0:00:00
[16:22:46.550] Collecting redis<5.0.0,>=4.3.5
[16:22:46.556]   Downloading redis-4.5.1-py3-none-any.whl (238 kB)
[16:22:46.565]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.5/238.5 kB 38.3 MB/s eta 0:00:00
[16:22:46.671] Collecting rich<13.0.0,>=12.6.0
[16:22:46.682]   Downloading rich-12.6.0-py3-none-any.whl (237 kB)
[16:22:46.690]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 237.5/237.5 kB 42.3 MB/s eta 0:00:00
[16:22:46.781] Collecting fastapi<0.89.0,>=0.88.0
[16:22:46.787]   Downloading fastapi-0.88.0-py3-none-any.whl (55 kB)
[16:22:46.793]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 11.5 MB/s eta 0:00:00
[16:22:46.864] Collecting plotly<6.0.0,>=5.10.0
[16:22:46.870]   Downloading plotly-5.13.1-py2.py3-none-any.whl (15.2 MB)
[16:22:47.005]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.2/15.2 MB 94.6 MB/s eta 0:00:00
[16:22:47.176] Collecting typing-extensions>=4.1.0
[16:22:47.183]   Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[16:22:47.247] Collecting click<9.0.0,>=7.1.1
[16:22:47.251]   Downloading click-8.1.3-py3-none-any.whl (96 kB)
[16:22:47.258]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 22.9 MB/s eta 0:00:00
[16:22:47.370] Collecting starlette==0.22.0
[16:22:47.375]   Downloading starlette-0.22.0-py3-none-any.whl (64 kB)
[16:22:47.382]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.3/64.3 kB 14.0 MB/s eta 0:00:00
[16:22:47.472] Collecting anyio<5,>=3.4.0
[16:22:47.476]   Downloading anyio-3.6.2-py3-none-any.whl (80 kB)
[16:22:47.483]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 kB 16.6 MB/s eta 0:00:00
[16:22:47.491] Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn<21.0.0,>=20.1.0->pynecone) (58.1.0)
[16:22:47.545] Collecting httpcore<0.17.0,>=0.15.0
[16:22:47.549]   Downloading httpcore-0.16.3-py3-none-any.whl (69 kB)
[16:22:47.556]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.6/69.6 kB 16.8 MB/s eta 0:00:00
[16:22:47.592] Collecting certifi
[16:22:47.595]   Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
[16:22:47.603]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 29.3 MB/s eta 0:00:00
[16:22:47.631] Collecting rfc3986[idna2008]<2,>=1.3
[16:22:47.635]   Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
[16:22:47.661] Collecting sniffio
[16:22:47.665]   Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
[16:22:47.703] Collecting tenacity>=6.2.0
[16:22:47.707]   Downloading tenacity-8.2.1-py3-none-any.whl (24 kB)
[16:22:47.755] Collecting bidict>=0.21.0
[16:22:47.760]   Downloading bidict-0.22.1-py3-none-any.whl (35 kB)
[16:22:47.810] Collecting python-engineio>=4.3.0
[16:22:47.814]   Downloading python_engineio-4.3.4-py3-none-any.whl (52 kB)
[16:22:47.820]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.9/52.9 kB 11.3 MB/s eta 0:00:00
[16:22:47.856] Collecting async-timeout>=4.0.2
[16:22:47.861]   Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
[16:22:47.900] Collecting commonmark<0.10.0,>=0.9.0
[16:22:47.904]   Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
[16:22:47.911]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 10.7 MB/s eta 0:00:00
[16:22:47.955] Collecting pygments<3.0.0,>=2.6.0
[16:22:47.961]   Downloading Pygments-2.14.0-py3-none-any.whl (1.1 MB)
[16:22:47.978]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 75.1 MB/s eta 0:00:00
[16:22:48.452] Collecting SQLAlchemy<=1.4.41,>=1.4.17
[16:22:48.458]   Downloading SQLAlchemy-1.4.41-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
[16:22:48.479]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 91.8 MB/s eta 0:00:00
[16:22:48.568] Collecting sqlalchemy2-stubs
[16:22:48.574]   Downloading sqlalchemy2_stubs-0.0.2a32-py3-none-any.whl (191 kB)
[16:22:48.582]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.6/191.6 kB 36.5 MB/s eta 0:00:00
[16:22:48.632] Collecting h11>=0.8
[16:22:48.644]   Downloading h11-0.14.0-py3-none-any.whl (58 kB)
[16:22:48.651]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 12.5 MB/s eta 0:00:00
[16:22:48.750] Collecting idna
[16:22:48.754]   Downloading idna-3.4-py3-none-any.whl (61 kB)
[16:22:48.761]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 11.1 MB/s eta 0:00:00
[16:22:49.083] Collecting greenlet!=0.4.17
[16:22:49.088]   Downloading greenlet-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (610 kB)
[16:22:49.101]      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 610.9/610.9 kB 60.1 MB/s eta 0:00:00
[16:22:49.579] Installing collected packages: rfc3986, commonmark, websockets, typing-extensions, tenacity, sniffio, python-engineio, pygments, psutil, idna, h11, gunicorn, greenlet, cloudpickle, click, certifi, bidict, async-timeout, uvicorn, typer, sqlalchemy2-stubs, SQLAlchemy, rich, redis, python-socketio, pydantic, plotly, anyio, starlette, sqlmodel, httpcore, httpx, fastapi, pynecone
[16:23:00.837] Successfully installed SQLAlchemy-1.4.41 anyio-3.6.2 async-timeout-4.0.2 bidict-0.22.1 certifi-2022.12.7 click-8.1.3 cloudpickle-2.2.1 commonmark-0.9.1 fastapi-0.88.0 greenlet-2.0.2 gunicorn-20.1.0 h11-0.14.0 httpcore-0.16.3 httpx-0.23.3 idna-3.4 plotly-5.13.1 psutil-5.9.4 pydantic-1.10.2 pygments-2.14.0 pynecone-0.1.18 python-engineio-4.3.4 python-socketio-5.7.2 redis-4.5.1 rfc3986-1.5.0 rich-12.6.0 sniffio-1.3.0 sqlalchemy2-stubs-0.0.2a32 sqlmodel-0.0.8 starlette-0.22.0 tenacity-8.2.1 typer-0.4.2 typing-extensions-4.5.0 uvicorn-0.20.0 websockets-10.4
[16:23:00.838] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[16:23:00.950] 
[16:23:00.950] [notice] A new release of pip available: 22.3.1 -> 23.0.1
[16:23:00.950] [notice] To update, run: pip install --upgrade pip
[16:23:02.098] Traceback (most recent call last):
[16:23:02.099]   File "/usr/local/bin/pc", line 5, in <module>
[16:23:02.099]     from pynecone.pc import main
[16:23:02.099]   File "/usr/local/lib/python3.9/site-packages/pynecone/__init__.py", line 6, in <module>
[16:23:02.099]     from .app import App
[16:23:02.099]   File "/usr/local/lib/python3.9/site-packages/pynecone/app.py", line 16, in <module>
[16:23:02.099]     from pynecone.model import Model
[16:23:02.099]   File "/usr/local/lib/python3.9/site-packages/pynecone/model.py", line 3, in <module>
[16:23:02.099]     import sqlmodel
[16:23:02.099]   File "/usr/local/lib/python3.9/site-packages/sqlmodel/__init__.py", line 130, in <module>
[16:23:02.099]     from .engine.create import create_engine as create_engine
[16:23:02.099]   File "/usr/local/lib/python3.9/site-packages/sqlmodel/engine/create.py", line 2, in <module>
[16:23:02.099]     import sqlite3
[16:23:02.099]   File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
[16:23:02.099]     from sqlite3.dbapi2 import *
[16:23:02.100]   File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
[16:23:02.100]     from _sqlite3 import *
[16:23:02.100] ModuleNotFoundError: No module named '_sqlite3'
[16:23:02.206] Error: Command "pc run" exited with 1
[16:23:02.340]

**Comment by demka-live** [comment]
It seems you have no sqlite3 installed on your system.
Try installing `sqlite-devel` (or `libsqlite3-dev`on some Debian-based systems).
Also the output says that you are running pip under root which is not a good way to install packages. You might want to use [venv](https://docs.python.org/3/library/venv.html).
Hope this helps!

**Comment by funprogrammer89** [comment]
You might be right that this is the issue. Vercel does not allow Sqlite as far as I can tell... aw shucks,
