### ISSUE TITLE
NPM fallback if Bun doesn't work on system

### ISSUE THREAD

**Issue by SpyderRex** [pynecone-io/pynecone#672]
**Describe the bug**
I use the command of run, but it throws an error saying the bun file does not exist, even though it does and it is on my PATH. I am using a Linux os on Android, namely Userland Ubuntu. When I type "which bun", it gives the exact same path that it uses when it says the file cannot be found.

**Traceback**
userland@localhost:~/PyneProj$ pc run
────────────────── Starting Pynecone App ──────────────────
────────────── Installing frontend packages ───────────────
Traceback (most recent call last):
  File "/usr/local/bin/pc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/pynecone/pc.py", line 120, in run
    frontend_cmd(app.app, Path.cwd(), frontend_port)
  File "/usr/local/lib/python3.10/dist-packages/pynecone/utils.py", line 634, in run_frontend
    setup_frontend(root)
  File "/usr/local/lib/python3.10/dist-packages/pynecone/utils.py", line 615, in setup_frontend
    install_frontend_packages()
  File "/usr/local/lib/python3.10/dist-packages/pynecone/utils.py", line 458, in install_frontend_packages
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/userland/.bun/bin/bun'

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: 0.1.20
 - OS: Linux
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
I see, can you try putting that path from `which bun` in your pcconfig for bun_path and see if you still get the error

**Comment by SpyderRex** [comment]
You're referring to the config.py file, am I correct? I tried that and it
is still throwing up the same error. It is still saying the file does not
exist, even though it does.

**Comment by SpyderRex** [comment]
I think I figured it out. As far as I can tell, there isn't a 32-bit
version of bun and my system happens to be 32-bit (armv7l). I should have
specified that. Sorry for the confusion. Is there another way to use
Pynecone with my architecture?

**Comment by Alek99** [comment]
Got it we need to make a fallback to npm if the system does not support bun.

Will get this in one of the next releases.

**Comment by Alek99** [comment]
Now that I am thinking more about this feature I am going to make an argument in the pcconfig to not use bun. That way we don't manually have to keep track of which os works with that dependency.
