### ISSUE TITLE
Error while runing init project

### ISSUE THREAD

**Issue by Shoothzj** [pynecone-io/pynecone#674]
**Describe the bug**
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/@chakra-ui/accordion/dist/chakra-ui-accordion.esm.js:8:0
Module not found: Can't resolve '@chakra-ui/descendant'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./pages/_app.js

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
error - ./node_modules/@chakra-ui/accordion/dist/chakra-ui-accordion.esm.js:8:0
Module not found: Can't resolve '@chakra-ui/descendant'

Import trace for requested module:
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js
./pages/_app.js

https://nextjs.org/docs/messages/module-not-found
error - Error: Cannot find module '/Users/akka/code/python/my_app_name/.web/.next/fallback-build-manifest.json'
Require stack:
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next-server.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/lib/start-server.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/cli/next-dev.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/lib/commands.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.loadDefaultErrorComponents (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/dev/next-dev-server.js:1008:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next-server.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/lib/start-server.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/cli/next-dev.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/lib/commands.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/bin/next'
  ]
}
Error: Cannot find module '/Users/akka/code/python/my_app_name/.web/.next/fallback-build-manifest.json'
Require stack:
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next-server.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/lib/start-server.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/cli/next-dev.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/lib/commands.js
- /Users/akka/code/python/my_app_name/.web/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.loadDefaultErrorComponents (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/dev/next-dev-server.js:1008:43)
    at async DevServer.renderErrorToResponse (/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/base-server.js:1111:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/load-components.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next-server.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/next.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/server/lib/start-server.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/cli/next-dev.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/lib/commands.js',
    '/Users/akka/code/python/my_app_name/.web/node_modules/next/dist/bin/next'
  ]
}
```

**To Reproduce**
```
$ mkdir my_app_name
$ cd my_app_name
$ pc init
```

**Expected behavior**

**Screenshots**
<img width="379" alt="image" src="https://user-images.githubusercontent.com/12933197/224915721-37e4f330-6d1a-48f0-827e-19689e5dfcc8.png">

** Specifics (please complete the following information):**
 - Python Version: 3.9.6
 - Pynecone Version: 0.1.20
 - OS:  ARM OSX
 - Browser (Optional): Chrome

**Comment by Shoothzj** [comment]
Thanks for building such library. Did I miss anthing?
<img width="396" alt="image" src="https://user-images.githubusercontent.com/12933197/224918632-574738be-0198-4b1e-97ed-87c6260f3936.png">

**Comment by Alek99** [comment]
I haven't seen this error before is anyone else getting this?

**Comment by Shoothzj** [comment]
@Alek99 Thanks for your reply. I fixed it by manually install nextjs.
