### ISSUE TITLE
SyntaxError: The requested module '@socket.io/component-emitter' does not provide an export named 'Emitter'

### ISSUE THREAD

**Issue by panxiaoguang** [pynecone-io/pynecone#710]
after `pc run`, I got a error

```
───────────────────────────────────────────────────── Starting Pynecone App ─────────────────────────────────────────────────────
───────────────────────────────────────────────── Installing frontend packages ──────────────────────────────────────────────────
bun install v0.5.5 (242dcea2)
────────────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────────
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
(node:741830) ExperimentalWarning: The ESM module loader is experimental.
event - compiled client and server successfully in 2.2s (760 modules)
wait  - compiling / (client and server)...
wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 738 ms (897 modules)
error - file:///home/panxiaoguang/%E6%96%87%E6%A1%A3/test/test2/.web/node_modules/engine.io-client/build/esm-debug/transport.js:2
import { Emitter } from "@socket.io/component-emitter";
         ^^^^^^^
SyntaxError: The requested module '@socket.io/component-emitter' does not provide an export named 'Emitter'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24) {
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 190 ms (898 modules)
```

**Comment by Alek99** [comment]
What os are you on?

**Comment by panxiaoguang** [comment]
> What os are you on?

CentOS 8 stream

**Comment by panxiaoguang** [comment]
I know the reason, It's because the version of nodejs
