### ISSUE TITLE
Unexpected Event Type When Event Chaining

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#777]
**Describe the bug**

When running both the snake game and clock there is an error in the latest version of pynecone.

```
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<AsyncServer._handle_event_internal() done, defined at /Users/alekpetuskey/Library/Caches/pypoetry/virtualenvs/pynecone-Ap6ViQ6z-py3.10/lib/python3.10/site-packages/socketio/asyncio_server.py:522> exception=AssertionError("Unexpected event type, <class 'method'>.")>
Traceback (most recent call last):
  File "/Users/alekpetuskey/Library/Caches/pypoetry/virtualenvs/pynecone-Ap6ViQ6z-py3.10/lib/python3.10/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/Users/alekpetuskey/Library/Caches/pypoetry/virtualenvs/pynecone-Ap6ViQ6z-py3.10/lib/python3.10/site-packages/socketio/asyncio_server.py", line 569, in _trigger_event
    return await self.namespace_handlers[namespace].trigger_event(
  File "/Users/alekpetuskey/Library/Caches/pypoetry/virtualenvs/pynecone-Ap6ViQ6z-py3.10/lib/python3.10/site-packages/socketio/asyncio_namespace.py", line 37, in trigger_event
    ret = await handler(*args)
  File "/Users/alekpetuskey/Desktop/pynecone/pynecone/app.py", line 582, in on_event
    update = await process(self.app, event, sid, headers, client_ip)
  File "/Users/alekpetuskey/Desktop/pynecone/pynecone/app.py", line 438, in process
    update = await state.process(event)
  File "/Users/alekpetuskey/Desktop/pynecone/pynecone/state.py", line 579, in process
    events = fix_events(events, event.token)
  File "/Users/alekpetuskey/Desktop/pynecone/pynecone/event.py", line 352, in fix_events
    assert isinstance(e, EventSpec), f"Unexpected event type, {type(e)}."
```
**To Reproduce**
 - Code/Link to Repo:

Clock code in examples repo.

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.21
 - OS:  Mac

**Comment by picklelo** [comment]
Found the root cause was the line
```python
self.state.convert_handlers_to_fns()
```

We added this so we could call event handlers from other event handlers. But it breaks the case of returning event handlers...  We need to either change the API or do something under the hood. For the under the hood conversion to event handlers, I'm not sure how to handle the case of passing in arguments is the only issue.
