### ISSUE TITLE
Can't use pc.select or pc.radio_group with a list declared in State. TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by jq6l43d1** [pynecone-io/pynecone#821]
**Describe the bug**
Can't use pc.select or pc.radio_group with a list declared in State. When I do I get "TypeError: issubclass() arg 1 must be a class"

**To Reproduce**

This code works:
```
options = ["Option 1", "Option 2", "Option 3"]

class RadioState(pc.State):

def index():
    return pc.vstack(
        pc.radio_group(
            options,
        ),
    )
```

This code doesn't work
```
class RadioState(pc.State):

options = ["Option 1", "Option 2", "Option 3"]

def index():
    return pc.vstack(
        pc.radio_group(
            State.options,
        ),
    )
```
Declaring the list like the following makes no difference:

`options: list = ["test", "test2", "test3"]`

**If you change pc.radio_group to pc.select in the above examples the results are the same.**

**Expected behavior**
I expected for a radio_group to a appear on my page but instead I got an error.

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.24
 - OS: Ubuntu 22.04
 
**Stacktrace**

```
Traceback (most recent call last):
  File "/home/user/.local/bin/pc", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/pc.py", line 106, in run
    app = prerequisites.get_app()
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/utils/prerequisites.py", line 100, in get_app
    return __import__(module, fromlist=(constants.APP_VAR,))
  File "/home/user/code/ai-tools-website/ai_tools_website/ai_tools_website.py", line 1500, in <module>
    app.compile()
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/app.py", line 404, in compile
    compiler.compile_page(route, component, self.state)
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/compiler/compiler.py", line 126, in wrapper
    path, code = fn(*args)
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/compiler/compiler.py", line 193, in compile_page
    code = _compile_page(component, state)
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/compiler/compiler.py", line 73, in _compile_page
    render=component.render(),
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 388, in render
    tag = self._render()
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/layout/cond.py", line 54, in _render
    true_value=self.comp1.render(),
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in render
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 398, in <listcomp>
    [str(tag.contents)] + [child.render() for child in self.children]
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/component.py", line 389, in render
    return str(
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/tags/tag.py", line 141, in __str__
    props_str = self.format_props()
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/tags/tag.py", line 128, in format_props
    return os.linesep.join(
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/tags/tag.py", line 129, in <genexpr>
    f"{name}={self.format_prop(prop)}"
  File "/home/user/.local/lib/python3.10/site-packages/pynecone/components/tags/tag.py", line 70, in format_prop
    if issubclass(prop.type_, str):
TypeError: issubclass() arg 1 must be a class
```

**Comment by jq6l43d1** [comment]
Here is a simple example program that fails to run. I've tried pynecone versions 0.1.24 through 0.1.16 as well as trying to run the code on a different computer with a fresh install of pynecone and I get the same error.

```
import pynecone as pc

class State(pc.State):
    """The app state."""
    options = ["Option 1", "Option 2", "Option 3"]

def index() -> pc.Component:
    return pc.center(
        pc.vstack(
            pc.select(
                State.options,
            ),

        ),
    )
# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Comment by ElijahAhianyo** [comment]
debugged this on a call with @jq6l43d1 , and this gives an error on python3.10.7. It worked once we switched to 3.11.1. I have a fair idea of what the issue is. Would look into this
