### ISSUE TITLE
value prop in pc.input and pc.editable seems buggy

### ISSUE THREAD

**Issue by ElijahAhianyo** [pynecone-io/pynecone#853]
Setting the value prop for `pc.input` and `pc.editable` doesnt allow you to type in the input field. Tested this out in a new react app and problem still persists. Perhaps it has something to do with react than chakraUI?

**To Reproduce**
 https://pynecone.io/docs/library/forms/input

**Expected behavior**
Should be able to type in input field

**Comment by masenf** [comment]
When I try it, I get a warning on the console:

```
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at /Users/masen/code/pynecone-io/repro-853/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at /Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/input/dist/chakra-ui-input.cjs.dev.js:72:24
    at div
    at /Users/masen/code/pynecone-io/repro-853/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:51:25
    at Component (webpack-internal:///./pages/index.js:32:88)
    at EnvironmentProvider (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.cjs.dev.js:120:24)
    at ColorModeProvider (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.cjs.dev.js:228:21)
    at ThemeProvider (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/@emotion/react/dist/emotion-element-b63ca7c6.cjs.dev.js:106:21)
    at ThemeProvider (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/system/dist/chakra-ui-system.cjs.dev.js:57:27)
    at /Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at /Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.cjs.dev.js:265:23
    at ChakraProvider (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/@chakra-ui/provider/dist/chakra-ui-provider.cjs.dev.js:40:24)
    at MyApp (webpack-internal:///./pages/_app.js:23:18)
    at StyleRegistry (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/Users/masen/code/pynecone-io/repro-853/.web/node_modules/next/dist/server/render.js:614:21)
```

On the client side, wiring up the `value` prop to state (or literal) means that the input can never change. Every time the value changes, react will re-render the component back to the state-derived value.

So, I do agree this is "weird", but I think it's kind of par-for-the-course for controlled inputs and the warning does point you in the right direction: use `default_value`...although that doesn't allow the state to actually update the input value after the initial load, so it's not a _real_ solution.
