### ISSUE TITLE
Shouldn't have to pass `self` when chaining event handlers

### ISSUE THREAD

**Issue by masenf** [pynecone-io/pynecone#920]
**Describe the bug**

When chaining `EventHandlers`, pynecone-0.1.27 requires `self` to be passed explicitly, even though the method appears to be bound to self already. This is unusual and a behavioral difference from 0.1.24

**To Reproduce**

```python
import pynecone as pc


class State(pc.State):
    val: str = "unset"

    def c1a(self):
        return self.c2

    def c1b(self):
        return self.c2("foo")

    def c1b_workaround(self):
        return self.c2(self, "foo")

    def c2(self, val="bar"):
        self.val = val


def index() -> pc.Component:
    return pc.center(
        pc.vstack(
            pc.heading(State.val, font_size="2em"),
            pc.hstack(
                pc.button("c1a: 'bar'", on_click=State.c1a),
                pc.button("c1b: 'foo'", on_click=State.c1b),
                pc.button("c1b-workaround", on_click=State.c1b_workaround),
            ),
        ),
        padding_top="10%",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Expected behavior**
Expect `c1b` handler to ultimately set the `val` to "foo". Instead it raises an exception on the backend.

```console
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/pynecone/state.py", line 655, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "/Users/masen/code/pynecone-io/repro-event-chaining-self/repro_event_chaining_self/repro_event_chaining_self.py", line 11, in c1b
    return self.c2("foo")
           ^^^^^^^^^^^^^^
  File "/Users/masen/code/pynecone-io/repro-event-chaining-self/repro_event_chaining_self/repro_event_chaining_self.py", line 17, in c2
    self.val = val
    ^^^^^^^^
AttributeError: 'str' object has no attribute 'val'
```

** Specifics (please complete the following information):**
 - Python Version: 3.11.2
 - Pynecone Version: 0.1.27
 - OS: macOS 13.2.1
 - Browser (Optional):
 
**Additional context**
Haven't done any further investigation, but I did make a comment about this [over here](https://github.com/pynecone-io/pynecone-examples/pull/59#discussion_r1181269953)

Issue doesn't repro on main, instead we hit https://github.com/pynecone-io/pcweb/issues/62 on `c1a` and `c2b` works fine (`c2b_workaround` blows up with a `TypeError: State.c2() takes from 1 to 2 positional arguments but 3 were given`)

**Comment by masenf** [comment]
Dupe of #896
